#!/usr/bin/env bash
set -e

if [ -z "$ROOT_PKG_PATH" ]
then
  echo "ROOT_PKG_PATH not set"
  exit 1
fi

if [ -z "$ROOTSYS" ]
then
  echo "ROOTSYS not set"
  exit 1
fi

pkg_name="$1"
pkg_dir=`realpath $2`
target_cmake="pkg-source/CMakeLists.txt"

rm -rf ~/.cache/root-pkgs/$pkg_name
mkdir -p ~/.cache/root-pkgs/$pkg_name
cd ~/.cache/root-pkgs/$pkg_name

cp -r "$pkg_dir" pkg-source
echo -e "cmake_minimum_required(VERSION 3.7)\n$(cat $target_cmake)" > "$target_cmake"
echo -e "include(RootFramework)\n$(cat $target_cmake)" > "$target_cmake"

mkdir build
cd build

cmake "-DCMAKE_INSTALL_PREFIX=$ROOT_PKG_PATH/$pkg_name" "-DCMAKE_MODULE_PATH=$ROOTSYS/etc/cmake" -DCMAKE_EXPORT_COMPILE_COMMANDS=On -GNinja  ../pkg-source
cmake --build .
cmake --install
