#!/usr/bin/env bash

set -e

if [ -z "$ROOT_PKG_PATH" ]
then
  echo "ROOT_PKG_PATH not set"
  exit 1
fi

if [ -z "$ROOTSYS" ]
then
  echo "ROOTSYS not set"
  exit 1
fi

pkg_name="$1"
cd ~/.cache/root-pkgs/$pkg_name

archive_dir="${pkg_name}_package_source"

# List files available for install
unzip -l ${pkg_name}.zip | sed '1,3d;$d' | sed '$d'

# Unzip package into install location
unzip ${pkg_name}.zip -d $ROOT_PKG_PATH/$pkg_name/
