#!/usr/bin/env bash
set -e

if [ -z "$ROOT_PKG_PATH" ]
then
  echo "ROOT_PKG_PATH not set"
  exit 1
fi

if [ -z "$ROOTSYS" ]
then
  echo "ROOTSYS not set"
  exit 1
fi

pkg_name="$1"
cd ~/.cache/root-pkgs/$pkg_name
archive_dir="${pkg_name}_package_source"
mkdir $archive_dir

###
# Copying includes
cp -R build/inc $archive_dir
# Copying includes
cp -R build/lib* $archive_dir
# Copying rootmap
cp -R build/*.rootmap  $archive_dir
# Copying pcms
cp -R build/*.pcm  $archive_dir
# Copying README
cp -R $ROOTSYS/README $archive_dir
# Copying LICENSE
cp -R $ROOTSYS/LICENSE $archive_dir
###
# Creating a package
cd $archive_dir
zip -r ../${pkg_name}.zip *
