#!/usr/bin/env python

import argparse
import sys
import os
import yaml
import zipfile

def zipdir(path, ziph):
    for root, dirs, files in os.walk(path):
        for file in files:
            ziph.write(os.path.join(root, file))
