#!/usr/bin/env bash
set -e

if [ -z "$ROOT_PKG_PATH" ]
then
  echo "ROOT_PKG_PATH not set"
  exit 1
fi

if [ -z "$ROOTSYS" ]
then
  echo "ROOTSYS not set"
  exit 1
fi

pkg_name="$1"
rootsources="$2"

subdircount=`find $rootsources -type d -name "$pkg_name"`

if [ $subdircount ]
then
    return 1
else
    return 0
fi
