#!/usr/bin/env bash
set -e

if [ -z "$ROOT_PKG_PATH" ]
then
  echo "ROOT_PKG_PATH not set"
  exit 1
fi

if [ -z "$ROOTSYS" ]
then
  echo "ROOTSYS not set"
  exit 1
fi

pkg_name="$1"
cd ~/.cache/root-pkgs/$pkg_name

cd build

#cmake --debug-output --build .
ninja -v
